repos:
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        args:
        - --max-line-length=88

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
        - --max-line-length=88

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-ast
    -   id: detect-aws-credentials
        args: ['--allow-missing-credentials']
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: detect-private-key
    -   id: check-merge-conflict

-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args:
        - -l
        - --recursive
        - -x
        - tests
        - -s
        - B201,B104
        files: .py$

-   repo: local
    hooks:
    -   id: tests
        pass_filenames: false
        name: pytest
        entry: pytest -v
        language: system
        types: [python]
