name: CI Pipeline

on: push

jobs:
  pipeline:
    name: Pipeline Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0