name: release
on:
  push:
    tags:
      - 'v*'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: pex
  REGION: us-central1
jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker gcr.io

      - name: wait for docker image
        run: timeout 5m bash -c 'until skopeo inspect docker://gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} 2> /dev/null; do sleep 10; done'

      - name: tag image with version
        run: gcloud container images add-tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$(cat VERSION)
